# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'Reminders_UIKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Reminders_UIKit
  pod 'RxCocoa'
  pod 'RxSwift'
  pod 'SnapKit'
  pod 'Then'
  pod 'UITextView+Placeholder'

  post_install do |installer|
    installer.generated_projects.each do |project|
      project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        end
      end
    end
  end

end
